teacher:
  weights_uri: "s3://models/student_v1.pt"
  weights_cache_dir: "models/teacher/weights_cache"

  device: "cuda:0"
  imgsz: 1280
  conf_th: 0.25
  iou: 0.7
  max_det: 300
  agnostic_nms: false
  classes: null
  max_fail_samples: 1000

  save_conf: false
  enable_vis: true
  vis_dir: "logs/teacher_vis"

  min_boxes_for_success: 2
  min_conf_for_success: 0.55
  min_box_area_norm: 0.0002
  max_boxes_per_image: 50

  keep_classes: null
